### ISSUE TITLE
Mistake in documentation

### ISSUE THREAD

**Issue by bgnq** [Mapotempo/optimizer-api#5]
Hello,

In swagger.json, Vehicle definition's part :  

```
  {
    "id": "vehicle_id-1",
    "router_mode": "car",
    "router_dimension": "time",
    "speed_multiplier": 1.0,
    "sequence_timewindows": [{
        "day_index": 0,
        "start": 25200,
        "end": 57600
    }, {
        "day_index": 1,
        "start": 25200,
        "end": 57600
    }, {
        "day_index": 2,
        "start": 25200,
        "end": 57600
    }, {
        "day_index": 3,
        "start": 25200,
        "end": 57600
    }, {
        "day_index": 4,
        "start": 25200,
        "end": 57600
    }],
    "start_point_id": "store",
    "end_point_id": "store",
    "unavailable_work_day_indices": [5, 7]
  }
```
Indice 7 for the day does not exist (between 0, 6)

`"unavailable_work_day_indices": [5, 6]`

Thank

**Comment by braktar** [comment]
The JSON is correct : 
timewindows day_index are between 0 and 6 describing week days from monday to sunday. (sequence_timewindows are duplicated all over the period)

unavailable_work_day_indices are refering the overall period days, defined within the configuration -> schedule part.

**Comment by bgnq** [comment]
ok thanks
