### ISSUE TITLE
Testing sequence_timewindows

### ISSUE THREAD

**Issue by bgnq** [Mapotempo/optimizer-api#8]
Hello,

I test sequence_timewindows with this [JSON](https://gist.github.com/bgnq/f0f9b12daf0dd8856deb98b867f29587)

But the vehicle work only one day, is there an error in the JSON ?

Thanks !

**Comment by braktar** [comment]
Hello,

You didn't defined the schedule range to consider within the configuration part : 
```
"schedule": {
          "range_indices": {
            "start": 0,
            "end": 5
          }
        }
```

**Comment by bgnq** [comment]
Perfect, thanks !
